# Use the official Python image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy requirements.txt first to leverage Docker cache
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Add this line to ensure python-dotenv is installed
RUN pip install python-dotenv

# Copy the rest of the application code
COPY . .

# Expose port if necessary (for HTTP or other services)
# EXPOSE 8000

# Command to run the application
CMD ["python", "subscriber.py"]
