# Stage 1
FROM maven:3.9.0-eclipse-temurin-17 AS build


WORKDIR /app

COPY pom.xml ./
RUN mvn dependency:go-offline

COPY src ./src

RUN mvn clean install

# Stage 2
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY --from=build /app/target/abonnee-service-0.0.1-SNAPSHOT.jar /app/abonnee-service.jar


ENTRYPOINT ["java", "-jar", "/app/abonnee-service.jar"]
