# Example Dockerfile
# Build Stage
FROM maven:3.8.5-openjdk-17-slim AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn dependency:go-offline -B
RUN mvn clean package -DskipTests

# Runtime Stage
FROM eclipse-temurin:20-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Start de applicatie
CMD ["java", "-jar", "app.jar"]

EXPOSE 8080

